# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1irXpAWWgSQO9CqQ7fDro9QD0sinb2LFb
"""

import pandas as pd
from sklearn.datasets import fetch_california_housing

# Cargar datos
data = fetch_california_housing(as_frame=True)
df = data.frame

# Estadísticas básicas
print(df.describe())